-- Create SPRING_SESSION table
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME INTEGER NOT NULL,
    LAST_ACCESS_TIME INTEGER NOT NULL,
    MAX_INACTIVE_INTERVAL INTEGER NOT NULL,
    EXPIRY_TIME INTEGER NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

-- Create SPRING_SESSION_ATTRIBUTES table
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS usuarios (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(30),
	last_name VARCHAR(30),
	age INTEGER,
	email VARCHAR(60)
);


INSERT INTO usuarios(name, last_name, age, email) VALUES ('Elena', 'Rodriguez', 32, 'elena.rodriguez@example.com');
INSERT INTO usuarios(name, last_name, age, email) VALUES ('Carlos', 'Fernandez', 28, 'carlos.fernandez@example.net');
INSERT INTO usuarios(name, last_name, age, email) VALUES ('María', 'Gonzalez', 35, 'maria.gonzalez@example.org');
INSERT INTO usuarios(name, last_name, age, email) VALUES ('Juan', 'Perez', 40, 'juan.perez@example.co');
INSERT INTO usuarios(name, last_name, age, email) VALUES ('Ana', 'Lopez', 26, 'ana.lopez@example.io');

SELECT * FROM usuarios;